config/routes.rb
# frozen_string_literal: true

Contact::Application.routes.draw do
  # This route is for eliminating the default devise sign up
  devise_for :admins
  # devise_for :admins, controllers: { registrations: 'admin/registrations' }

  resources :email_contacts
  get '/thankyou', to: 'email_contacts#thankyou'
  root to: 'email_contacts#new'

  devise_scope :admin do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessor :email, :password, :password_confirmation, :remember_me

  # validates :email, email: true
end

app/models/email_contact.rb
# frozen_string_literal: true

class EmailContact < ActiveRecord::Base
  # attr_accessible :name, :email, :subject, :message
  # attr_accessor :name, :email, :subject, :message

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,    presence: true, length: { maximum: 50 }
  validates :email,   presence: true, format: { with: email_regex }
  validates :subject, presence: true, length: { maximum: 80 }
  validates :message, presence: true, length: { maximum: 500 }
end

app/controllers/admins_controller.rb
# frozen_string_literal: true

class AdminsController < ApplicationController
  def new
    # redirect_to root_path
  end

  #  ##  This is dummy code.
  #   def show
  #    redirect_to email_contacts
  #   end
  #
  #   def index
  #    redirect_to email_contacts
  #   end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

require 'ap' unless Rails.env.production?

class ApplicationController < ActionController::Base
  protect_from_forgery

  # def after_sign_in_path_for(resource)
  #   session["user_return_to"] || root_path
  # end
end

app/controllers/email_contacts_controller.rb
# frozen_string_literal: true

class EmailContactsController < ApplicationController
  def index
    if admin_signed_in?
      @email_contacts = EmailContact.all
      respond_to do |format|
        format.html
        format.xml { render xml: @email_contacts }
      end
    else
      redirect_to root_path
    end
  end

  def show
    # TODO: add authorization here.  This should be redundant,
    # an unauthorized user should never get here.
    if admin_signed_in?
      @email_contact = EmailContact.find(params[:id])
      respond_to do |format|
        format.html
        format.xml { render xml: @email_contact }
      end
    else
      redirect_to root_path
    end
  end

  def new
    @email_contact = EmailContact.new

    respond_to do |format|
      format.html
      format.xml { render xml: @email_contact }
    end
  end

  def edit
    redirect_to email_contacts_path
    # @email_contact = EmailContact.find(params[:id])
  end

  def permitted_params
    params.require(:email_contact).permit(:email, :subject, :message, :name)
  end

  def create
    @email_contact = EmailContact.new(permitted_params)

    respond_to do |format|
      if @email_contact.save
        deliver
        format.html { redirect_to(thankyou_path, notice: 'Email contact was successfully created.') }
        format.xml  { render xml: @email_contact, status: :created, location: @email_contact }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @email_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @email_contact = EmailContact.find(params[:id])

    respond_to do |format|
      if @email_contact.update_attributes(permitted_params)
        format.html { redirect_to(@email_contact, notice: 'Email contact was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @email_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def thankyou
    @thanks = 'Come back soon!'
    render('email_contacts/thankyou')
  end

  # TODO: Add authentication so users not signed
  #       cannot delete.
  def destroy
    @email_contact = EmailContact.find(params[:id])
    @email_contact.destroy

    respond_to do |format|
      format.html { redirect_to(email_contacts_url) }
      format.xml  { head :ok }
    end
  end

  private

  def deliver
    # ContactMailer.welcome_email(@email_contact).deliver
    ContactMailer.contacts_copy(@email_contact).deliver
    ContactMailer.daves_copy(@email_contact).deliver
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  def new
    ap '#__FILE__}'
    # redirect_to root_path
  end

  # def create
  #   # add custom create logic here
  # end
  #
  # def update
  #   super
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/email_contacts_helper.rb
# frozen_string_literal: true

module EmailContactsHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

app/views/email_contacts/_form.html.erb
<div class="contactform span-11">

  <h2 class="contactform">Send me an email!</h2>
  
<%= form_for(@email_contact) do |f| %>
  <% if @email_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_contact.errors.count, "error") %> prohibited this email_contact from being saved:</h2>

      <ul>
      <% @email_contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Send it!"%>
  </div>
<% end %>
</div>

app/views/email_contacts/edit.html.erb
<h2>Editing email_contact</h2>

<%= render 'form' %>

<%= link_to 'Show', @email_contact %> |
<%= link_to 'Back', email_contacts_path %>

app/views/email_contacts/index.html.erb
<h2>Emails</h2>


<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Subject</th>
    <th>Message</th>
    <th></th>
<!--
    <th></th>
-->
    <th></th>
  </tr>

<% @email_contacts.each do |email_contact| %>
  <tr>
    <td><%= email_contact.name %></td>
    <td>
      <%= email_contact.email %>
    </td>
    <td>
      <%= email_contact&.subject[0..30] %>
    </td>
    <td>
      <%= email_contact&.message[0..30] %>
    </td>
    <td><%= link_to 'Show', email_contact %></td>
    <!--
    <td><%= link_to 'Edit', edit_email_contact_path(email_contact) %></td>
    -->
    <td><%= link_to 'Delete', email_contact, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/email_contacts/new.html.erb
<div class="span-17 last">

<%= render 'form' %>

<%= render 'layouts/sidebar' %>
</div>

app/views/email_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @email_contact.name %>
</p>

<p>
  <b>Email:</b>
  <%= @email_contact.email %>
</p>

<p>
  <b>Subject:</b>
  <%= @email_contact.subject %>
</p>

<p>
  <b>Message:</b>
  <%= @email_contact.message %>
</p>

<%= link_to 'Delete', email_contact_path(@email_contact), :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back to list', email_contacts_path %>

app/views/email_contacts/thankyou.html.erb
<p>Thanks for contacting me, I'll get back to you momentarily.  -Dave Doolin</p>

app/views/layouts/_footer.html.erb
<footer class="span-18 last">


<%= link_to 'New email message', new_email_contact_path %>
<% if admin_signed_in? %>
|
<%= link_to 'List', email_contacts_path %>
|
<%= link_to 'Logout', logout_path %>
<% else %>
|
<%= link_to 'Login', login_path %>
<% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="header">

<h1><%= link_to 'Contact David M. Doolin', root_path %> </h1>

<!-- 
<div id="admin_nav">  
  <% if admin_signed_in? %>  
    Signed in as <%= current_admin.email %>. Not you?  
    <%= link_to "Sign out", destroy_admin_session_path %>  
  <% else %>  
    <%= link_to "Sign in", new_admin_session_path %>  
  <% end %>  
</div>  
-->

</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar span-6 last">

<h2 class="sidebar">I'm here and there...</h2>


        <table>
          <!-- 
          <tr class="spacer"> 
            <td class="f">&nbsp;</td> 
            <td class="v">&nbsp;</td> 
          </tr>
          --> 
          <tr class="tel"> 
            <td class="f type"><img src="/images/iphone_16.png" /></td> 
            <td class="v value"><a href="tel:1-510-984-2480">510-334-4006</a></td> 
          </tr> 
          <!--
          <tr class="spacer"> 
            <td class="f">&nbsp;</td> 
            <td class="v">&nbsp;</td> 
          </tr> 
          <tr> 
            <td class="f">aim</td> 
            <td class="v"><a id="aim" class="url im offline" href="aim:goim?screenname=jaredhanson@mac.com">jaredhanson@mac.com</a></td> 
          </tr> 
          <tr> 
            <td class="f">jabber</td> 
            <td class="v"><a id="gtalk" class="url im offline" href="xmpp:jaredhanson@gmail.com">jaredhanson@gmail.com</a></td> 
          </tr> 
          <tr> 
            <td class="f">msn</td> 
            <td class="v"><a id="msn" class="url im offline" href="msnim:chat?contact=jared.hanson@hotmail.com">jared.hanson@hotmail.com</a></td> 
          </tr>
          --> 
          <tr> 
            <td class="f"><img src="/images/skype.ico" /></td> 
            <td class="v"><a id="skype" class="url im offline" href="skype:mtngrown?chat">mtngrown</a></td> 
          </tr> 
          <!--
          <tr> 
            <td class="f">yahoo</td> 
            <td class="v"><a id="yahoo" class="url im offline" href="ymsgr:sendIM?jared.hanson">jared.hanson</a></td> 
          </tr>
          --> 
          <tr class="spacer"> 
            <td class="f">&nbsp;</td> 
            <td class="v">&nbsp;</td> 
          </tr> 
          <tr> 
            <td class="f"><img width="16" height="16" src="/images/linkedin.ico" /></td> 
            <td class="v"><a id="linkedin" target="_blank" class="url sn" href="http://www.linkedin.com/in/davidmdoolin" rel="me">linkedin.com/in/davidmdoolin</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/github.ico" /></td> 
            <td class="v"><a id="github" target="_blank" class="url sn" href="http://github.com/doolin" rel="me">github.com/doolin</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/feed.png" /></td> 
            <td class="v"><a id="blog" target="_blank" class="url sn" href="http://daviddoolin.com/" rel="me">daviddoolin.com</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/twitter.ico" /></td> 
            <td class="v"><a id="twitter" target="_blank" class="url sn" href="http://twitter.com/doolin" rel="me">twitter.com/doolin</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/facebook.ico" /></td> 
            <td class="v"><a id="facebook" target="_blank" class="url sn" href="http://www.facebook.com/David.Doolin" rel="me">facebook.com/David.Doolin</a></td> 
          </tr> 
          <!-- 
          <tr> 
            <td class="f">flickr</td> 
            <td class="v"><a id="flickr" class="url sn" href="http://www.flickr.com/photos/jaredhanson/" rel="me">flickr.com/photos/jaredhanson</a></td> 
          </tr> 
          <tr> 
            <td class="f">youtube</td> 
            <td class="v"><a id="youtube" class="url sn" href="http://www.youtube.com/jaredhanson" rel="me">youtube.com/jaredhanson</a></td> 
          </tr> 
          -->          
          <tr class="spacer"> 
            <td class="f">&nbsp;</td> 
            <td class="v">&nbsp;</td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/inventium.png" /></td> 
            <td class="v"><a id="inventium" target="_blank" class="url sn" href="http://inventiumsystems.com/" rel="me">inventium systems</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/wiaw_favicon.png" /></td> 
            <td class="v"><a id="wiaw" target="_blank" class="url sn" href="http://website-in-a-weekend.net/" rel="me">website in a weekend</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/hrecipe_icon.png" /></td> 
            <td class="v"><a id="hrecipe" target="_blank" class="url sn" href="http://hrecipe.com/" rel="me">hrecipe for wordpress</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/tinobox_icon.png" /></td> 
            <td class="v"><a id="tinobox" target="_blank" class="url sn" href="http://tinobox.com/wordpress/" rel="me">there is no box</a></td> 
          </tr> 
          <tr> 
            <td class="f"><img src="/images/house_icon.png" /></td> 
            <td class="v"> 
              <div class="adr"> 
                <span class="locality">San Francisco East Bay</span>,
                <span class="region">CA</span> 
                <div class="country-name">United States</div> 
              </div> 
            </td> 
          </tr> 
        </table> 



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact David Doolin</title>
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
    <%= javascript_include_tag :defaults %>
    <script type="text/javascript" src="http://use.typekit.com/mzf5uva.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="container">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>